### ISSUE TITLE
Error retrieving data

### ISSUE THREAD

**Issue by southrock70** [jbaurle/PMStockQuote#1]
Starting yesterday PMScotckQute stops getting data:

ERROR: Couldn't   retrieve and/or process financial data from internet service. Internal   message: The remote server returned an error: (403) Forbidden.
--

This is the error, anyone more that got this

**Comment by jbaurle** [comment]
Hi,

Thanks for your message. The Stock Quote add-in is using the Yahoo Finance service to retrieve the stock quotes. The service seems to be terminated by Yahoo without any notice. I’m using the tool myself and now try to find an alternative, but I'm not sure how long it will take.

Jürgen

[cid:image001.png@01D354D7.159D79A0]


Von: southrock70 [mailto:notifications@github.com]
Gesendet: Freitag, 3. November 2017 18:42
An: jbaurle/PMStockQuote <PMStockQuote@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [jbaurle/PMStockQuote] Error retrieving data (#1)


Starting yesterday PMScotckQute stops getting data:

ERROR: Couldn't retrieve and/or process financial data from internet service. Internal message: The remote server returned an error: (403) Forbidden.

This is the error, anyone more that got this

**Comment by southrock70** [comment]
Bummer, not OK from Yahoo :-(
What do you need from a service? I can also look for an alterntive source.

**Comment by ebernhard1** [comment]
I first started seeing this error two or three days ago... PLEASE PLEASE find a fix - I LOVE this add-on...

**Comment by jvietor** [comment]
Yes, happened to me also, sigh....

**Comment by jvietor** [comment]
so Yahoo cut off the Yahoo Finance Service on Nov 1 due to "breach of Terms of Service".  No word on replacement or anything.  https://forums.yahoo.net/t5/Yahoo-Finance-help/Yahoo-stock-quote-downloads-US-stocks/td-p/387410

**Comment by jbaurle** [comment]
Hi,

Thanks for your message. The Stock Quote add-in is using the Yahoo Finance service to retrieve the stock quotes. The service seems to be terminated by Yahoo without any notice. I’m using the tool myself and now try to find an alternative, but I'm not sure how long it will take.

Jürgen

[cid:image001.png@01D35549.B104C610]


Von: jvietor [mailto:notifications@github.com]
Gesendet: Samstag, 4. November 2017 03:52
An: jbaurle/PMStockQuote <PMStockQuote@noreply.github.com>
Cc: Jürgen Bäurle <jbaeurle@parago.de>; Comment <comment@noreply.github.com>
Betreff: Re: [jbaurle/PMStockQuote] Error retrieving data (#1)


so Yahoo cut off the Yahoo Finance Service on Nov 1 due to "breach of Terms of Service". No word on replacement or anything. https://forums.yahoo.net/t5/Yahoo-Finance-help/Yahoo-stock-quote-downloads-US-stocks/td-p/387410

**Comment by jbaurle** [comment]
The Stock Quote add-in is using the Yahoo Finance service to retrieve the stock quotes. The service seems to be terminated by Yahoo without any notice. I’m using the tool myself on a daily basis. I'll try to find an alternative, but I'm not sure how long it will take. May be we can use Google Finance.

**Comment by valueshopper** [comment]
Prior to "Stock Quote" I used a screen scrape but looking at  source code for Yahoo's current quote page a screen scrape would no longer work.  The MSN product I once tried was limited to I believe 165 stocks and since I monitor roughly 3200 it was useless to me.  Based on my investing style an end-of-day price would be good enough but I don't know if most people using the "Stock Quote" could work with end of day or would need something closer to real time/intraday.

**Comment by valueshopper** [comment]
By the way, I tried to go to Yahoo's portfolio page and when adding stocks I pasted in a list of about 2200 tickers and it accepted it, which surprised me.

**Comment by valueshopper** [comment]
One difference I see between Yahoo and Google is that in Yahoo the US tickers are entered without exchange or country specified and any ticker from outside the US got an exchange suffix.  On the other hand, in Google Finance (using Google Chrome) if you enter a ticker without an exchange specified it presumes you mean that ticker in your home country.  For example for me a Canadian, entering "L" on Google Finance using Google Chrome gives the price of the Canadian grocer Loblaws. If I want to see the price of the US company Lowes I must enter "NYSE:L"  Also, if I wanted to be more certain, for Loblaws I could enter "TSE:L"  
Any use of Google Finance would want to ensure that people in different countries all get the same answer when entering a given ticker so you would want the exchange always specified.  Obviously I realize that browser experience may not equate to API experience but it is worth noting and understanding the Google functionality.

**Comment by ebernhard1** [comment]
Any solution yet in sight?

**Comment by ebernhard1** [comment]
HELP??!!??

**Comment by jbaurle** [comment]
I'm currently checking out if we can use Google Finance to replace the Yahoo API. There are not a lot of free services that provide international stock quotes or do not need any API keys.

**Comment by jvietor** [comment]
I found this tool, so far it works but needs to be stripped down and some of the fluff removed.  I don’t know VBASIC otherwise I’d do it myself. 

http://investexcel.net/multiple-stock-quote-downloader-for-excel/

**Comment by SNike05** [comment]
I don't know anything about coding. 
Please see TradingView's charting library API or check out these mobile apps to find out where they are sourcing data from "Stock Quote" and "Portfolio Watcher" I use both these free apps for my stocks. The latter developer is very active and constantly updating his app.
